version: '3'
services:

        redis:
            container_name: redis
            image: redis
            restart: always
            command: ["redis-server", "--appendonly", "yes"]
            ports:
                - "6379:6379"
            volumes:
                - redis-data:/data

        web:
            build: ./web
            command: bash -c "python manage.py runserver 0.0.0.0:8000"
            restart: always
            ports:
                - "8000:8000"
            volumes:
                - ./web:/web
            depends_on:
                - redis

        bot:
            build: ./bot
            command: bash -c "python admin_bot.py"
            restart: always
            volumes:
                - ./bot:/bot
            depends_on:
                - web
            network_mode: "host"


volumes:
        redis-data:
        pgdata:
